# Generated by Django 4.2.2 on 2023-06-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_changed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=25)),
                ('price', models.DecimalField(decimal_places=5, max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('instrument', models.CharField(choices=[('1', 'EUR/USD'), ('2', 'USD/CHF'), ('3', 'GBP/USD'), ('4', 'NZD/USD'), ('5', 'AUD/USD'), ('6', 'USD/JPY'), ('7', 'EUR/CAD'), ('8', 'EUR/AUD'), ('9', 'EUR/CHF')], max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_changed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=25)),
                ('price', models.DecimalField(decimal_places=5, max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('instrument', models.CharField(choices=[('1', 'EUR/USD'), ('2', 'USD/CHF'), ('3', 'GBP/USD'), ('4', 'NZD/USD'), ('5', 'AUD/USD'), ('6', 'USD/JPY'), ('7', 'EUR/CAD'), ('8', 'EUR/AUD'), ('9', 'EUR/CHF')], max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
