# Generated by Django 4.2.2 on 2023-06-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_changed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=25)),
                ('price', models.DecimalField(decimal_places=5, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('instrument', models.CharField(choices=[(1, 'USD/CAD'), (2, 'EUR/USD'), (3, 'USD/CHF'), (4, 'GBP/USD'), (5, 'NZD/USD'), (6, 'AUD/USD'), (7, 'USD/JPY'), (8, 'EUR/CAD'), (9, 'EUR/AUD'), (10, 'EUR/AUD')], max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_changed', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=25)),
                ('price', models.DecimalField(decimal_places=5, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('instrument', models.CharField(choices=[(1, 'USD/CAD'), (2, 'EUR/USD'), (3, 'USD/CHF'), (4, 'GBP/USD'), (5, 'NZD/USD'), (6, 'AUD/USD'), (7, 'USD/JPY'), (8, 'EUR/CAD'), (9, 'EUR/AUD'), (10, 'EUR/AUD')], max_length=9)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
